### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by PythonLinks** [scrapper/perobs#1]
In the code in the redme, you said "merry", I think you meant "marry".
Other than that.  What  a great idea.  I am currently using ZODB on Python, but sadly Python only supports one thread at a time.  Maybe now there is shared memory between processes.  

In general, I am moving away from Python, just as it is becoming the most popular language, ruby has a much better multi-processing story.  Most needed now.  But I do need to model trees and graphs.  Not sure what I am going to do. 

I wish I better understood why Python gives a slightly more elegant persistent object graph model than ruby.  The problem is I do not yet know the internals for ruby.

**Comment by scrapper** [comment]
Thanks! I've fixed the typo.
