### ISSUE TITLE
Lessons From the ZODB

### ISSUE THREAD

**Issue by PythonLinks** [scrapper/perobs#2]
First of all thank you for this great work. The idea of a persistent graph of Ruby objects is a very important concept, and it was the one thing that Ruby lacked. It was the one thing holding me back from ditching Python and moving to Ruby. Now I see a path forward. 

I am a Python/ZODB developer, who is increasingly moving to Ruby.  The thing that Python lacks is simultaneous multi-threading.  What Python does have, and Ruby lacks,  is the ZODB. 

ZODB gives you a very clean and mature model of a graph of persistent objects.   You can either store ZODB objects in FileStorage, or in RelStorage.  RelStorage is very heavily used and quite mature.  
https://dev.nextthought.com/blog/2019/11/relstorage-30.html

The ZODB object model is a bit cleaner than PerObs. I think PerObs can learn a lesson from ZODB.  ZODB does not really use proxy objects.  Instead the proxy/ghost objects load the content and become the object. 

How does ZODB achieve such a brilliant persistent object abstraction?  The magic is in class persistent.  

https://github.com/zopefoundation/persistent/blob/master/persistent/persistence.py

Why is there a difference between Ruby and Python? (This problem kept me up for 2 hours last night) Well Ruby and Python are a bit different.  Python provides a __getattr__  and __setattr__ method which ZODB overrides to load the data if needed. Ruby does not have that.  Each attribute has its own getter and setter methods.  So to do this in Ruby one would have to rewrite all of the getter and setters.  

I think we could do that automatically.  When first loading the application, we could rewrite all of the getters and setters, to use the ZODB persistent Ghost model.  Then we would have a gorgeous persistent object model in Ruby. 

The other thing the ZODB community would want, is a way to use the persistent ruby objects. It would be quite easy to store Ruby Objects in FileStorage or RelStorage.  Right now ZODB objects are serialized with Pickle, but they could be easily serialized with another format. Json is one obvious option.  VelocityPack for ArrangoDB has a great reputation.  The convert command could move them to that format.   Then we could all use our persistent Python objects in Ruby!  Hurrah!

So I think I can get fully transparent persistent objects in Ruby.  I think I can share them with the Python objects in ZODB.  And then eventually we can figure out how to use Ruby’s 3.0 concurrent threads.

**Comment by scrapper** [comment]
I'm not sure what to do here? Ruby does have Object.instance_variable_set and *_get.
